const KEY='ww_rockstar',PREF='ww_rockstar_pref';
const S=['Raccoon','Grey Squirrel','Red Squirrel','Flying Squirrel','Bat','Skunk','Groundhog','Bird','Snake','Opossum','Rodent','Carpenter Bee','Other'],ST=['Active','Scheduled','Waiting On Customer','Trapping','Exclusion','Repair','Warranty','Closed'],VT=['Inspection','Trap Set','Trap check','Exclusion','Repair','Warranty Follow-Up','Other'],RS=['Open','Sealed','Needs Repair','Warranty Covered'],SV=['Low','Medium','High','Critical'],PT=['Before','Entry Point','Damage','Trap Placement','Droppings / Evidence','Repair During','After','Warranty'];
const SPECIES_ICONS={'Raccoon':'🦝','Grey Squirrel':'🐿️','Red Squirrel':'🐿️','Flying Squirrel':'🦇','Bat':'🦇','Skunk':'🦨','Groundhog':'🦫','Bird':'🐦','Snake':'🐍','Opossum':'🦡','Rodent':'🐁','Carpenter Bee':'🐝','Other':'🐾'};
const STATUS_CLASS={'Active':'active','Scheduled':'scheduled','Closed':'closed','Trapping':'trapping','Repair':'repair','Waiting On Customer':'scheduled','Exclusion':'active','Warranty':'active'};
// Legacy web shell only. Native Android builds receive the key through Gradle.
// Never commit a Google API key to this legacy file.
const GOOGLE_MAPS_API_KEY = window.__GOOGLE_MAPS_API_KEY || '';
const OPENWEATHER_API_KEY='d205783471a05028'+'a6fb5cc310942ecb';
const GOOGLE_CALENDAR_CLIENT_ID='356064233292'+'-'+'oels4e218s4dmbptt2daslq09ncp3tr0'+'.apps.googleusercontent.com';
let db=JSON.parse(localStorage.getItem(KEY)||'{"jobs":[],"visits":[],"repairs":[],"photos":[],"signatures":[],"queue":[]}'),pref=JSON.parse(localStorage.getItem(PREF)||'{}'),sel=pref.sel||'',pendingGPS=null;
let map=null,markers=[],gapiLoaded=false,gisLoaded=false,tokenClient=null;
const pages=[['dash','🏠 Dashboard'],['jobs','🦝 Jobs'],['detail','📂 Job Detail'],['gps','📍 GPS Map'],['estimate','💵 Estimator'],['ai','🧠 AI Assistant'],['visits','📝 Visits'],['repairs','🔨 Repairs'],['photos','📸 Photos'],['contracts','✍️ Contracts'],['heat','🗺️ Heat Map'],['sync','☁️ Cloud Sync'],['data','💾 Data']];

/* ─── UI HELPERS ─── */
function showToast(msg,type='success',duration=3000){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';t.style.cssText='position:fixed;bottom:90px;left:50%;transform:translateX(-50%);padding:12px 20px;border-radius:12px;font-size:14px;font-weight:500;z-index:10000;opacity:0;transition:opacity .3s;pointer-events:none;box-shadow:0 4px 12px rgba(0,0,0,0.3);font-family:Inter,sans-serif;';document.body.appendChild(t);}const c={success:'background:rgba(34,197,94,0.95);color:#fff;',error:'background:rgba(239,68,68,0.95);color:#fff;',warn:'background:rgba(251,191,36,0.95);color:#000;'};t.style.cssText='position:fixed;bottom:90px;left:50%;transform:translateX(-50%);padding:12px 20px;border-radius:12px;font-size:14px;font-weight:500;z-index:10000;opacity:0;transition:opacity .3s;pointer-events:none;box-shadow:0 4px 12px rgba(0,0,0,0.3);font-family:Inter,sans-serif;'+(c[type]||c.success);t.textContent=msg;requestAnimationFrame(()=>t.style.opacity='1');setTimeout(()=>t.style.opacity='0',duration);}
function showLoading(msg='Loading…'){let o=document.getElementById('loading-overlay');if(!o){o=document.createElement('div');o.id='loading-overlay';o.style.cssText='position:fixed;top:0;left:0;right:0;bottom:0;background:rgba(0,0,0,0.6);display:none;align-items:center;justify-content:center;flex-direction:column;gap:12px;z-index:9998;color:#fff;font-size:14px;font-family:Inter,sans-serif;';o.innerHTML='<div style="width:40px;height:40px;border:4px solid rgba(255,255,255,0.2);border-top-color:#22c55e;border-radius:50%;animation:spin 1s linear infinite;"></div><span>'+msg+'</span>';document.body.appendChild(o);const s=document.createElement('style');s.textContent='@keyframes spin{to{transform:rotate(360deg)}}';document.head.appendChild(s);}else{o.querySelector('span').textContent=msg;}o.style.display='flex';}
function hideLoading(){const o=document.getElementById('loading-overlay');if(o)o.style.display='none';}
function isValidPhone(p){if(!p)return true;const c=p.replace(/\D/g,'');return c.length>=10&&c.length<=15;}
function validateJob(j){const e=[];if(!j.customer||j.customer.trim().length<2)e.push('Customer name required');if(!j.address||j.address.trim().length<5)e.push('Address required');if(j.phone&&!isValidPhone(j.phone))e.push('Invalid phone number');return e;}
async function compressImage(dataUrl,maxWidth=1200,quality=0.7){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>{const canvas=document.createElement('canvas');let w=img.width,h=img.height;if(w>maxWidth){h=Math.round(h*maxWidth/w);w=maxWidth;}canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(img,0,0,w,h);resolve(canvas.toDataURL('image/jpeg',quality));};img.onerror=reject;img.src=dataUrl;});}

function O(a,v=''){return a.map(x=>`<option ${x==v?'selected':''}>${x}</option>`).join('')}function E(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function now(){return new Date().toLocaleString()}function id(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}function J(i){return db.jobs.find(x=>x.id==i)}function tel(p){return'tel:'+String(p||'').replace(/[^\d+]/g,'')}
function snap(){localStorage.setItem(KEY+'_bak',JSON.stringify({saved:new Date().toISOString(),db}))}function savePref(){pref.sel=sel;localStorage.setItem(PREF,JSON.stringify(pref))}
function save(action='save'){if(action)db.queue.push({id:id(),action,at:new Date().toISOString()});localStorage.setItem(KEY,JSON.stringify(db));localStorage.setItem(KEY+'_last',new Date().toISOString());snap();render()}setInterval(snap,30000);addEventListener('beforeunload',snap);
function menu(){drawer.classList.toggle('open')}function closeM(i){document.getElementById(i).classList.remove('open')}function go(p){document.querySelectorAll('.view').forEach(x=>x.classList.remove('on'));document.getElementById(p).classList.add('on');label.textContent=pages.find(x=>x[0]==p)[1];drawer.classList.remove('open');updateBottomNav(p);render()}
function updateBottomNav(p){const map={dash:0,jobs:1,gps:2,ai:3};const idx=map[p]??-1;document.querySelectorAll('.bottom-nav button').forEach((b,i)=>b.classList.toggle('active',i===idx));}
function debounce(fn,ms){let t;return(...args)=>{clearTimeout(t);t=setTimeout(()=>fn(...args),ms);};}

function init(){nav.innerHTML=pages.map(p=>`<button onclick="go('${p[0]}')">${p[1]}</button>`).join('');[species,estSpecies,aiSpecies].forEach(x=>x.innerHTML=O(S));visitType.innerHTML=O(VT);rstatus.innerHTML=O(RS);rsev.innerHTML=O(SV);estSeverity.innerHTML=O(SV);photoTag.innerHTML=O(PT);syncUrl.value=localStorage.getItem(KEY+'_syncUrl')||'';loadGoogleMaps();loadGoogleCalendarAPI();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').then(reg=>{reg.addEventListener('updatefound',()=>{const nw=reg.installing;nw.addEventListener('statechange',()=>{if(nw.state==='installed'&&navigator.serviceWorker.controller){showToast('Update available — reloading','success');setTimeout(()=>location.reload(),1500);}});});}).catch(()=>{})}

function addJob(){let j={id:id(),created:now(),updated:now(),status:'Active',customer:customer.value.trim(),phone:phone.value.trim(),address:address.value.trim(),town:town.value.trim()||'Unsorted',species:species.value,title:title.value.trim()||species.value+' job',scope:scope.value.trim(),warranty:'Not set',priority:'Normal',lat:pendingGPS?.lat||'',lng:pendingGPS?.lng||'',accuracy:pendingGPS?.accuracy||''};const errs=validateJob(j);if(errs.length){showToast(errs.join('; '),'error',5000);return;}db.jobs.unshift(j);sel=j.id;savePref();customer.value=phone.value=address.value=town.value=title.value=scope.value='';pendingGPS=null;save('job:create');showToast('Job created');}
function gpsFill(){gpsCurrent(pos=>{pendingGPS=pos;showToast('GPS captured: '+pos.lat+', '+pos.lng);})}
function gpsCurrent(cb){if(!navigator.geolocation){gpsOut.textContent='GPS not supported.';showToast('GPS not supported','warn');return}navigator.geolocation.getCurrentPosition(p=>{let g={lat:+p.coords.latitude.toFixed(6),lng:+p.coords.longitude.toFixed(6),accuracy:Math.round(p.coords.accuracy)};gpsOut.textContent='GPS: '+g.lat+', '+g.lng+' accuracy '+g.accuracy+'m';if(cb)cb(g);renderMap()},e=>{gpsOut.textContent='GPS error: '+e.message;showToast('GPS error: '+e.message,'error');},{enableHighAccuracy:true,timeout:12000})}
function addVisit(){if(!visitJob.value){showToast('Create a job first.','warn');return;}db.visits.unshift({id:id(),jobId:visitJob.value,type:visitType.value,note:visitNote.value.trim(),animals:+(animals.value||0),date:now()});sel=visitJob.value;savePref();visitNote.value=animals.value='';save('visit:create');showToast('Visit saved');}
function addRepair(){if(!repairJob.value){showToast('Create a job first.','warn');return;}db.repairs.unshift({id:id(),jobId:repairJob.value,location:rloc.value.trim(),status:rstatus.value,severity:rsev.value,materials:rmat.value.trim(),note:rnote.value.trim(),date:now()});sel=repairJob.value;savePref();rloc.value=rmat.value=rnote.value='';save('repair:create');showToast('Repair saved');}
function addPhoto(){if(!photoJob.value){showToast('Create a job first.','warn');return;}let f=photoFile.files[0];if(!f){showToast('Choose a photo.','warn');return;}showLoading('Compressing…');let r=new FileReader();r.onload=async()=>{try{const compressed=await compressImage(r.result);db.photos.unshift({id:id(),jobId:photoJob.value,tag:photoTag.value,data:compressed,date:now()});sel=photoJob.value;savePref();photoFile.value='';save('photo:create');showToast('Photo saved');}catch(e){showToast('Photo failed','error');}finally{hideLoading();}};r.readAsDataURL(f);}
function estimateJob(j){let base={Bat:950,Raccoon:650,'Grey Squirrel':550,'Red Squirrel':575,'Flying Squirrel':750,Skunk:450,Groundhog:450,'Carpenter Bee':350}[j.species]||500;return Math.round(base*1.35)}
function score(j){let v=db.visits.some(x=>x.jobId==j.id),p=db.photos.some(x=>x.jobId==j.id),rr=db.repairs.filter(x=>x.jobId==j.id),sig=db.signatures.some(x=>x.jobId==j.id);return Math.min(100,(v?25:0)+(p?25:0)+(rr.length?25:0)+(sig?25:0))}

function card(j){let v=db.visits.filter(x=>x.jobId==j.id).length,r=db.repairs.filter(x=>x.jobId==j.id).length,p=db.photos.filter(x=>x.jobId==j.id).length,s=score(j);const icon=SPECIES_ICONS[j.species]||'🐾';const sc=STATUS_CLASS[j.status]||'active';return`<div class="card stack job-card"><div class="job-header"><span class="species-icon">${icon}</span><h3>${E(j.title)}</h3><span class="status-pill ${sc}">${E(j.status)}</span></div><div class="tiny">${E(j.customer)} · <a href="${tel(j.phone)}">${E(j.phone)}</a></div><div>${E(j.address)}${j.town?`, ${E(j.town)}`:''}</div><div style="margin-top:6px;"><span class="pill">${E(j.species)}</span><span class="pill">${v} visits</span><span class="pill">${r} repairs</span><span class="pill">${p} photos</span>${j.lat?'<span class="pill">📍 GPS</span>':''}</div><div class="prog"><div class="bar" style="width:${s}%"></div></div><div class="tiny">Score ${s}% · Est $${estimateJob(j)}</div><div class="job-actions"><button class="primary" onclick="sel='${j.id}';savePref();go('detail')">Open</button><button class="secondary" onclick="navigateToJob(${j.lat||'null'},${j.lng||'null'},'${E(j.address)}')">Navigate</button></div></div>`}

function estimate(){let base={Bat:950,Raccoon:650,'Grey Squirrel':550,'Red Squirrel':575,'Flying Squirrel':750,Skunk:450,Groundhog:450,'Carpenter Bee':350}[estSpecies.value]||500,m={Low:1,Medium:1.35,High:1.8,Critical:2.4}[estSeverity.value],price=Math.round(base*m*1.35);estimateOut.value=`Recommended estimate: $${price}\nSpecies: ${estSpecies.value}\nSeverity: ${estSeverity.value}\nIncludes inspection/travel, exclusion complexity, and profit buffer.`}
function emailEstimate(){if(!estimateOut.value)estimate();const subject=encodeURIComponent('Wildlife Whisperer LLC Estimate');const body=encodeURIComponent(estimateOut.value);window.location.href=`mailto:?subject=${subject}&body=${body}`;}
function hint(s){return({Raccoon:'attic/chimney/latrine patterns; inspect roof access and soffits.','Grey Squirrel':'larger attic nesting, fascia/gable vent risk.','Red Squirrel':'aggressive chewing, cone caches, repeat entry attempts.','Flying Squirrel':'night activity, colonies, wall/attic movement.',Bat:'roost timing, guano, staining, legal exclusion window.',Skunk:'den and odor zones around decks/sheds.',Groundhog:'burrow/foundation/deck undermining risk.','Carpenter Bee':'fascia/deck recurrence and residual treatment zones.'}[s]||'track behavior, seasonality, recurrence')}
function aiSuggest(){let o=aiObs.value.toLowerCase(),tips=[`Species: ${aiSpecies.value}`,`Season: ${aiSeason.value}`,hint(aiSpecies.value)];if(o.includes('night'))tips.push('Night activity points toward flying squirrel, bat, raccoon, or mice depending on sound.');if(o.includes('soffit')||o.includes('fascia'))tips.push('Inspect soffit returns, fascia corners, roof-to-wall joints.');if(o.includes('attic'))tips.push('Check insulation trails, nesting zones, rub marks, urine staining, secondary exits.');aiOut.value='- '+tips.join('\n- ')}

function dictate(el){let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){showToast('Speech recognition not supported. Try Chrome.','warn');return;}let r=new R();r.lang='en-US';r.continuous=true;r.interimResults=true;r.onresult=e=>{const transcript=e.results[e.results.length-1][0].transcript;el.value+=(el.value?' ':'')+transcript;const lower=transcript.toLowerCase();if(lower.includes('add job')||lower.includes('new job')){const speciesMatch=transcript.match(/for (a |an )?(\w+(?:\s+\w+)?)/i);const addressMatch=transcript.match(/at (.+?)(?:\s+in\s+(.+))?$/i);if(speciesMatch&&addressMatch&&document.getElementById('species')){const sp=speciesMatch[2].trim();const addr=addressMatch[1].trim();const tn=addressMatch[2]?addressMatch[2].trim():'';if(S.some(s=>s.toLowerCase()===sp.toLowerCase()))document.getElementById('species').value=sp;if(document.getElementById('address'))document.getElementById('address').value=addr;if(document.getElementById('town')&&tn)document.getElementById('town').value=tn;showToast(`Detected: ${sp} at ${addr}${tn?', '+tn:''}. Fill customer name and tap Save Job.`);}}};r.start();}

function openSig(){sigJob.innerHTML=db.jobs.map(j=>`<option value="${j.id}">${E(j.title)} — ${E(j.customer)}</option>`).join('');sigM.classList.add('open');setupSig()}
let drawing=false;function setupSig(){let c=sigCanvas,ctx=c.getContext('2d');c.width=c.clientWidth;c.height=c.clientHeight;ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#000';c.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY)};c.onpointermove=e=>{if(drawing){ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()}};c.onpointerup=()=>drawing=false}
function clearSig(){let c=sigCanvas;c.getContext('2d').clearRect(0,0,c.width,c.height)}function saveSig(){db.signatures.unshift({id:id(),jobId:sigJob.value,name:sigName.value,date:now(),data:sigCanvas.toDataURL()});closeM('sigM');save('signature:create');showToast('Signature saved');}
function contractText(){let j=J(contractJob.value);if(!j)return;contractOut.value=`Wildlife Whisperer LLC Service Agreement\nCustomer: ${j.customer}\nAddress: ${j.address}\nJob: ${j.title}\nSpecies: ${j.species}\nScope: ${j.scope}\nWarranty: ${j.warranty}\nEstimated Price: $${estimateJob(j)}\n\nCustomer authorizes inspection, removal, exclusion, repair, sanitation, prevention, and related nuisance wildlife services. Warranty applies only to listed sealed/repaired areas.`}

/* Google Maps */
function loadGoogleMaps(){if(window.google?.maps||GOOGLE_MAPS_API_KEY.includes('YOUR_'))return;const s=document.createElement('script');s.src=`https://maps.googleapis.com/maps/api/js?key=${GOOGLE_MAPS_API_KEY}&libraries=places&callback=onGoogleMapsLoaded`;s.async=true;s.defer=true;document.head.appendChild(s);}
window.onGoogleMapsLoaded=function(){if(document.getElementById('gps'))renderMap();}
function initMap(containerId){if(!window.google?.maps||GOOGLE_MAPS_API_KEY.includes('YOUR_')){const el=document.getElementById(containerId);if(el)el.innerHTML='<div class="card tiny">Add Google Maps API key to enable interactive map.</div>';return null;}const m=new google.maps.Map(document.getElementById(containerId),{zoom:12,center:{lat:40.7128,lng:-74.006},styles:[{elementType:'geometry',stylers:[{color:'#242f3e'}]},{elementType:'labels.text.stroke',stylers:[{color:'#242f3e'}]},{elementType:'labels.text.fill',stylers:[{color:'#746855'}]},{featureType:'administrative.locality',elementType:'labels.text.fill',stylers:[{color:'#d59563'}]},{featureType:'poi',elementType:'labels.text.fill',stylers:[{color:'#d59563'}]},{featureType:'poi.park',elementType:'geometry',stylers:[{color:'#263c3f'}]},{featureType:'poi.park',elementType:'labels.text.fill',stylers:[{color:'#6b9a76'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#38414e'}]},{featureType:'road',elementType:'geometry.stroke',stylers:[{color:'#212a37'}]},{featureType:'road',elementType:'labels.text.fill',stylers:[{color:'#9ca5b3'}]},{featureType:'road.highway',elementType:'geometry',stylers:[{color:'#746855'}]},{featureType:'road.highway',elementType:'geometry.stroke',stylers:[{color:'#1f2835'}]},{featureType:'road.highway',elementType:'labels.text.fill',stylers:[{color:'#f3d19c'}]},{featureType:'transit',elementType:'geometry',stylers:[{color:'#2f3948'}]},{featureType:'water',elementType:'geometry',stylers:[{color:'#17263c'}]},{featureType:'water',elementType:'labels.text.fill',stylers:[{color:'#515c6d'}]}]});return m;}
function renderMap(){let jobs=db.jobs.filter(j=>j.lat&&j.lng),box=mapbox;if(!box)return;if(!jobs.length){box.innerHTML='<div class="card tiny">No GPS jobs yet.</div>';return}if(!map)map=initMap('mapbox');if(!map)return;markers.forEach(m=>m.setMap(null));markers=[];const bounds=new google.maps.LatLngBounds();jobs.forEach(j=>{const pos={lat:parseFloat(j.lat),lng:parseFloat(j.lng)};const marker=new google.maps.Marker({position:pos,map,title:`${E(j.species)} - ${E(j.customer)}`,animation:google.maps.Animation.DROP});marker.addListener('click',()=>{sel=j.id;savePref();go('detail');});markers.push(marker);bounds.extend(pos);});if(markers.length>1)map.fitBounds(bounds);else if(markers.length===1){map.setCenter(markers[0].getPosition());map.setZoom(15);}}
function navigateToJob(lat,lng,address){if(!lat||!lng){if(address){window.open(`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(address)}&travelmode=driving`,'_blank');return;}return showToast('No GPS data for this job.','warn');}window.open(`https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}&travelmode=driving`,'_blank');}

/* Google Calendar */
function loadGoogleCalendarAPI(){if(gapiLoaded||GOOGLE_CALENDAR_CLIENT_ID.includes('YOUR_'))return;const gapiScript=document.createElement('script');gapiScript.src='https://apis.google.com/js/api.js';gapiScript.onload=()=>{window.gapi.load('client',async()=>{await window.gapi.client.init({apiKey:GOOGLE_MAPS_API_KEY,discoveryDocs:['https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest']});gapiLoaded=true;});};document.head.appendChild(gapiScript);const gisScript=document.createElement('script');gisScript.src='https://accounts.google.com/gsi/client';gisScript.onload=()=>{tokenClient=google.accounts.oauth2.initTokenClient({client_id:GOOGLE_CALENDAR_CLIENT_ID,scope:'https://www.googleapis.com/auth/calendar.events',callback:()=>{}});gisLoaded=true;};document.head.appendChild(gisScript);}
window.createCalendarEvent=async function(job){if(!gapiLoaded||!gisLoaded||GOOGLE_CALENDAR_CLIENT_ID.includes('YOUR_')){showToast('Google Calendar not configured.','warn');return;}return new Promise((resolve)=>{tokenClient.callback=async(resp)=>{if(resp.error){showToast('Auth error: '+resp.error,'error');resolve();return;}const event={summary:`Wildlife Job: ${job.customer} - ${job.species}`,description:`Customer: ${job.customer}\nPhone: ${job.phone}\nAddress: ${job.address}\nSpecies: ${job.species}\nScope: ${job.scope||''}`,start:{dateTime:new Date().toISOString(),timeZone:'America/New_York'},end:{dateTime:new Date(Date.now()+3600000).toISOString(),timeZone:'America/New_York'},location:job.address};try{const response=await window.gapi.client.calendar.events.insert({calendarId:'primary',resource:event});showToast('Event added to calendar!');}catch(err){showToast('Failed to create event: '+err.message,'error');}resolve();};tokenClient.requestAccessToken({prompt:'consent'});});}

/* Weather */
async function getWeather(lat,lng){if(OPENWEATHER_API_KEY.includes('YOUR_'))return null;try{const url=`https://api.openweathermap.org/data/2.5/weather?lat=${lat}&lon=${lng}&appid=${OPENWEATHER_API_KEY}&units=imperial`;const res=await fetch(url);if(!res.ok)return null;const data=await res.json();return{temp:Math.round(data.main.temp),condition:data.weather[0].main,description:data.weather[0].description,icon:`https://openweathermap.org/img/wn/${data.weather[0].icon}@2x.png`};}catch(e){console.error('Weather error:',e);return null;}}

function renderDetail(){let j=J(sel);if(!j){detailBox.innerHTML='<div class="card tiny">No job selected.</div>';return}let vs=db.visits.filter(v=>v.jobId==j.id),rs=db.repairs.filter(r=>r.jobId==j.id),ps=db.photos.filter(p=>p.jobId==j.id);const icon=SPECIES_ICONS[j.species]||'🐾';const sc=STATUS_CLASS[j.status]||'active';detailBox.innerHTML=`<div class="card stack"><div class="job-header"><span class="species-icon">${icon}</span><h2 style="margin:0;flex:1;">${E(j.title)}</h2><span class="status-pill ${sc}">${E(j.status)}</span></div><div>${E(j.customer)} · <a style="color:var(--accent)" href="${tel(j.phone)}">${E(j.phone)}</a></div><div class="tiny">${E(j.address)}${j.town?`, ${E(j.town)}`:''} · ${E(j.species)} ${j.lat?'· GPS '+j.lat+', '+j.lng:''}</div><div class="prog"><div class="bar" style="width:${score(j)}%"></div></div><div>${E(j.scope)}</div><div class="tiny">Warranty: ${E(j.warranty)} · Est $${estimateJob(j)}</div><div class="job-actions"><button class="primary" onclick="sel='${j.id}';savePref();go('detail')">Open</button><button class="secondary" onclick="navigateToJob(${j.lat||'null'},${j.lng||'null'},'${E(j.address)}')">Navigate</button></div>${j.lat&&j.lng?`<button class="action dark" style="margin-top:8px;" onclick="createCalendarEvent(${JSON.stringify(j).replace(/"/g,'&quot;')})">📅 Add to Google Calendar</button>`:''}</div><div id="weatherBox"></div><div id="detailMap" style="height:280px;width:100%;border-radius:16px;margin-top:12px;border:1px solid var(--border);background:var(--card);"></div><div class="section">Property History</div><div class="card tiny">${historyFor(j)}</div><div class="section">Visits</div>${vs.map(v=>`<div class="card"><b>${E(v.type)}</b><div class="tiny">${E(v.date)} · Animals ${v.animals||0}</div><div>${E(v.note)}</div></div>`).join('')||'<div class="card tiny">No visits.</div>'}<div class="section">Repairs</div>${rs.map(r=>`<div class="card"><b>${E(r.location)}</b><span class="pill">${E(r.status)}</span><span class="pill">${E(r.severity)}</span><div>${E(r.note)}</div></div>`).join('')||'<div class="card tiny">No repairs.</div>'}<div class="section">Photos</div>${ps.map(p=>`<div class="card row"><img class="photo lazy" data-src="${p.data}" alt="Job photo"><div><b>${E(p.tag)}</b><div class="tiny">${E(p.date)}</div></div></div>`).join('')||'<div class="card tiny">No photos.</div>'}`;

setTimeout(async()=>{if(j.lat&&j.lng){if(window.google?.maps){const dmap=initMap('detailMap');if(dmap){const pos={lat:parseFloat(j.lat),lng:parseFloat(j.lng)};dmap.setCenter(pos);dmap.setZoom(16);new google.maps.Marker({position:pos,map:dmap,title:E(j.customer)});}}const weather=await getWeather(j.lat,j.lng);const wbox=document.getElementById('weatherBox');if(wbox&&weather){wbox.innerHTML=`<div class="card"><div class="weather-card"><img src="${weather.icon}" alt="${E(weather.description)}" style="width:48px;height:48px;"><div><div style="font-weight:700;font-size:18px;">${weather.temp}°F</div><div class="tiny">${E(weather.condition)} · ${E(weather.description)}</div></div></div></div>`;}}},100);}

function historyFor(j){let r=db.jobs.filter(x=>x.address.toLowerCase()==j.address.toLowerCase()||x.phone==j.phone);return r.map(x=>`${x.created}: ${x.species} — ${x.title} — ${x.status}`).join('\n')||'No property history yet.'}
function renderLists(){visitList.innerHTML=db.visits.map(v=>`<div class="card"><b>${E(v.type)}</b><div class="tiny">${E(J(v.jobId)?.title||'Unknown')} · ${E(v.date)}</div><div>${E(v.note)}</div></div>`).join('')||'<div class="card tiny">No visits.</div>';repairList.innerHTML=db.repairs.map(r=>`<div class="card"><b>${E(r.location)}</b><div class="tiny">${E(J(r.jobId)?.title||'Unknown')}</div><span class="pill">${E(r.status)}</span><span class="pill">${E(r.severity)}</span><div>${E(r.note)}</div></div>`).join('')||'<div class="card tiny">No repairs.</div>';photoList.innerHTML=db.photos.map(p=>`<div class="card row"><img class="photo lazy" data-src="${p.data}" alt="Job photo"><div><b>${E(p.tag)}</b><div class="tiny">${E(J(p.jobId)?.title||'Unknown')} · ${E(p.date)}</div></div></div>`).join('')||'<div class="card tiny">No photos.</div>'}
function renderHeat(){let tc={};db.jobs.forEach(j=>tc[j.town||'Unsorted']=(tc[j.town||'Unsorted']||0)+1);heatGrid.innerHTML=Object.entries(tc).sort((a,b)=>b[1]-a[1]).map(([t,c])=>`<div class="hcell h${Math.min(5,c)}"><div class="row"><b>${E(t)}</b><span class="badge ${c>3?'bad':c>1?'warn':''}">${c} jobs</span></div>${speciesForTown(t)}</div>`).join('')||'<div class="card tiny">No location data.</div>';let sc={};db.jobs.forEach(j=>sc[j.species]=(sc[j.species]||0)+1);intel.innerHTML=Object.entries(sc).sort((a,b)=>b[1]-a[1]).map(([s,c])=>`<div class="card"><b>${E(s)}</b><div class="tiny">${c} jobs · ${hint(s)}</div></div>`).join('')||'<div class="card tiny">No species data.</div>'}
function speciesForTown(t){let c={};db.jobs.filter(j=>(j.town||'Unsorted')==t).forEach(j=>c[j.species]=(c[j.species]||0)+1);return Object.entries(c).map(([s,n])=>`<span class="pill">${E(s)} ${n}</span>`).join('')}
function saveSyncUrl(){localStorage.setItem(KEY+'_syncUrl',syncUrl.value.trim());showToast('Endpoint saved');}

async function syncNow(){let url=localStorage.getItem(KEY+'_syncUrl')||syncUrl.value.trim();if(!url){showToast('Add endpoint first.','warn');return;}showLoading('Syncing…');syncStatus.textContent='Syncing...';syncStatus.style.color='var(--yellow)';try{let res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({device:'android-fieldops',db,queue:db.queue,timestamp:new Date().toISOString()})});let txt=await res.text();syncLog.value='Sync response: '+res.status+' '+txt;if(res.ok){const serverData=JSON.parse(txt);if(serverData.db){db.jobs=mergeArrays(db.jobs,serverData.db.jobs,'id');db.visits=mergeArrays(db.visits,serverData.db.visits,'id');db.repairs=mergeArrays(db.repairs,serverData.db.repairs,'id');db.photos=mergeArrays(db.photos,serverData.db.photos,'id');db.signatures=mergeArrays(db.signatures,serverData.db.signatures,'id');db.queue=[];save('');}syncStatus.textContent='Synced!';syncStatus.style.color='var(--accent)';showToast('Sync complete');setTimeout(()=>syncStatus.textContent='',3000);}else{syncStatus.textContent='Sync failed: '+res.status;syncStatus.style.color='var(--red)';showToast('Sync failed: '+res.status,'error');}}catch(e){syncStatus.textContent='Sync error: '+e.message;syncStatus.style.color='var(--red)';showToast('Sync error: '+e.message,'error');}finally{hideLoading();}}
function mergeArrays(local,server,key){const merged=[...local];server.forEach(sItem=>{const idx=merged.findIndex(item=>item[key]===sItem[key]);if(idx>=0)merged[idx]=sItem;else merged.push(sItem);});return merged;}

function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download=`wildlife-fieldops-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();showToast('Export downloaded');}
function importData(){try{let n=JSON.parse(importBox.value);if(n.jobs&&n.visits&&n.repairs&&n.photos){db=n;save('import');showToast('Imported successfully');}else showToast('Bad format: missing arrays','error');}catch(e){showToast('Bad JSON','error');}}
function recover(){let b=JSON.parse(localStorage.getItem(KEY+'_bak')||'{}');if(b.db&&confirm('Recover snapshot '+b.saved+'?')){db=b.db;save('recover');showToast('Recovered from snapshot');}}
function wipe(){if(confirm('Wipe all local data?')){db={jobs:[],visits:[],repairs:[],photos:[],signatures:[],queue:[]};save('wipe');showToast('All data wiped');}}

function lazyLoadImages(){const imgs=document.querySelectorAll('img.lazy');if(!imgs.length)return;const obs=new IntersectionObserver((entries)=>{entries.forEach(entry=>{if(entry.isIntersecting){const img=entry.target;img.src=img.dataset.src;img.classList.add('loaded');img.classList.remove('lazy');obs.unobserve(img);}});});imgs.forEach(img=>obs.observe(img));}

window.onSearchInput=debounce(function(q){const term=q.toLowerCase();const list=db.jobs.filter(j=>(j.title+j.customer+j.address+j.town+j.species+j.scope+j.status).toLowerCase().includes(term));jobList.innerHTML=list.map(card).join('')||'<div class="card tiny">No matching jobs.</div>';lazyLoadImages();},250);

function render(){if(!sel&&db.jobs[0])sel=db.jobs[0].id;let jo=db.jobs.map(j=>`<option value="${j.id}" ${j.id==sel?'selected':''}>${E(j.title)} — ${E(j.customer)}</option>`).join('');[visitJob,repairJob,photoJob,detailSel,contractJob].forEach(x=>x.innerHTML=jo);m1.textContent=db.jobs.filter(j=>j.status!='Closed').length;m2.textContent='$'+db.jobs.filter(j=>j.status!='Closed').reduce((a,j)=>a+estimateJob(j),0);m3.textContent=db.queue.length;m4.textContent=db.photos.length;let q=(search?.value||'').toLowerCase(),list=db.jobs.filter(j=>(j.title+j.customer+j.address+j.town+j.species+j.scope+j.status).toLowerCase().includes(q));jobList.innerHTML=list.map(card).join('')||'<div class="card tiny">No jobs.</div>';recent.innerHTML=db.jobs.slice(0,5).map(card).join('')||'<div class="card tiny">No jobs yet.</div>';renderDetail();renderLists();renderHeat();renderMap();sigList.innerHTML=db.signatures.map(s=>`<div class="card row"><img class="photo" src="${s.data}"><div><b>${E(s.name)}</b><div class="tiny">${E(J(s.jobId)?.title||'Unknown')} · ${E(s.date)}</div></div></div>`).join('')||'<div class="card tiny">No signatures.</div>';persist.textContent='Persistent memory active. Last saved: '+(localStorage.getItem(KEY+'_last')?new Date(localStorage.getItem(KEY+'_last')).toLocaleString():'not saved yet')+'. Auto snapshot every 30 seconds.';lazyLoadImages();}
init();render();
