package com.strobingn.wildlifefieldops.ai

/**
 * 25 standalone field AI tools for Wildlife FieldOps.
 * Each tool is offline-first and produces a copyable action report.
 */
object FieldAIFeatures {
    data class Feature(
        val id: String,
        val title: String,
        val category: String,
        val purpose: String,
        val steps: List<String>,
        val output: String
    )

    val all: List<Feature> = listOf(
        Feature("species_sign", "Species Sign Decoder", "ID", "Turn droppings, tracks, sounds, and damage into a ranked species list.", listOf("Photograph droppings, tracks, and chew marks with a scale.", "Note time of activity (dusk, night, dawn, day).", "Record attic, crawl, chimney, soffit, or yard location.", "Compare size: rice-grain = bats/mice, marble = squirrel, grape = raccoon."), "Most likely: raccoon if grape-size latrine + torn fascia. Squirrel if daytime + walnut chew + 2-3 in holes. Bat if dusk fly-out + staining under ridge/soffit."),
        Feature("entry_mapper", "Entry Point Mapper", "Inspection", "Walk the building in a fixed order so no gap is skipped.", listOf("Start at grade: foundation vents, dryer vents, garage corners.", "Walk soffit, fascia, rake, and chimney step-flashing.", "Check HVAC lines, cable, and plumbing penetrations.", "Mark each hole: size, substrate, animal evidence, photo ID."), "Primary entries first. Seal secondaries only after one-way or live-trap confirmation. Never seal occupied bat roosts in season."),
        Feature("exclusion_calc", "Exclusion Material Calculator", "Materials", "Estimate hardware cloth, flashing, and fasteners from measured openings.", listOf("Measure each opening width x height or linear gap.", "Add 2 in overlap on every edge.", "Use 1/4 in 16-ga cloth for bats/squirrels; 1/2 in 16-ga for raccoons.", "Count screws every 4-6 in plus flashing for wood-to-roof transitions."), "Rule of thumb: each typical soffit gap needs 12-18 in of cloth. A full fascia run of 40 ft needs about 45 ft of 12 in cloth plus 80-100 screws."),
        Feature("trap_interval", "Trap Check Interval Advisor", "Trapping", "Set legal and humane check windows by species and weather.", listOf("Know local check-interval law (often 24 hours; some areas 12).", "Increase frequency in heat, cold, rain, or public-view traps.", "Never leave a raccoon trap overnight in full sun.", "Log every check: empty, non-target, target, condition."), "Default: check every 12 hours in summer heat, every 24 hours in mild weather. Relocate or dispatch per permit the same visit."),
        Feature("season_calendar", "Hudson Valley Season Calendar", "Planning", "NY-region activity windows for common wildlife jobs.", listOf("Bats: maternity May-August. Do not exclude occupied roosts.", "Squirrels: two litters, spring and late summer.", "Raccoons: young in attics April-July.", "Skunks: denning late winter; kits May-June."), "Delay bat exclusion until fly-out confirmed after maternity. Inspect for juveniles before any one-way door."),
        Feature("ny_legal", "NY Legal / Permit Notes", "Compliance", "Field reminders for New York wildlife work. Not legal advice.", listOf("Nuisance Wildlife Control Operator (NWCO) rules apply.", "Some species require DEC authorization or cannot be relocated freely.", "Migratory birds and bats have extra federal protections.", "Document method, date, species, and disposal on every job."), "Do not relocate raccoons across counties without authorization. Do not exclude bats during maternity. Photograph evidence before work."),
        Feature("customer_script", "Customer Call Script", "Sales", "A calm, factual script for first-call booking.", listOf("Ask species signs, last seen, and where (attic, porch, yard).", "Ask about children, pets, and access (gate, tenant, HOA).", "Explain inspection first, then a written scope.", "Book the earliest window that matches activity time."), "Script: I need three facts: what you saw, where, and when. I will inspect the whole envelope, show you every opening, and price exclusion plus follow-up before we start."),
        Feature("estimate_builder", "Scope-to-Estimate Builder", "Pricing", "Turn inspection findings into line items, not a single lump.", listOf("Inspection / camera / attic access as its own line.", "Removal or one-way device as its own line.", "Each repair cluster (soffit, vent, chimney) separately.", "Cleanout, insulation, and warranty as optional add-ons."), "Never bury exclusion in a removal price. Customers accept repairs when they see each hole photographed and priced."),
        Feature("photo_prompts", "Photo Prompt Pack", "Documentation", "The 12 photos that close claims and callbacks.", listOf("Wide elevation of each wall.", "Close-up of every entry with a tape measure.", "Attic/crawl damage, droppings, insulation.", "Device placement, after-seal, and customer signature area."), "Name files jobId_before_01, _entry_03, _after_02. No photo = weak warranty defense."),
        Feature("callback_risk", "Callback Risk Scorer", "QA", "Score whether this job will come back in 30 days.", listOf("Unsealed secondaries add high risk.", "Unknown juveniles add high risk.", "Missing photos or warranty terms add medium risk.", "No follow-up trap-check scheduled adds high risk."), "High risk if any of: occupied den not confirmed empty, more than two unsealed gaps, or no 48-hour check booked."),
        Feature("ppe_selector", "PPE Selector", "Safety", "Pick PPE from the actual hazard, not habit.", listOf("Droppings / urine: P100 or N95, gloves, coveralls, eye protection.", "Live raccoon/skunk: bite-resistant gloves, face shield option.", "Attic fiberglass: long sleeves, knee pads, headlamp.", "Roof work: harness when pitch or height requires it."), "Histoplasmosis risk is real in attics. Never dry-sweep guano. Mist, bag, and ventilate."),
        Feature("bat_timing", "Bat Exclusion Timing", "Species", "Safe bat work for New York attics and soffits.", listOf("Watch a dusk fly-out before any seal.", "Do not exclude May through mid-August if pups may be present.", "Install tubes or one-ways on confirmed exits only.", "Seal the rest after 3-5 nights of zero activity."), "If you hear chirping in walls in June, stop. Return after maternity. Offer inspection plus monitoring now, exclusion later."),
        Feature("raccoon_den", "Raccoon Den Protocol", "Species", "Confirm occupancy before any seal.", listOf("Look for latrine, torn fascia, and 4 in+ openings.", "Use a camera or wait for night movement.", "If young are present, use eviction devices or wait, per law.", "Repair with 16-ga cloth plus wood or flashing, not foam alone."), "Foam-only repairs fail. Raccoons reopen them. Always mechanically fasten metal."),
        Feature("squirrel_door", "Squirrel One-Way Planner", "Species", "Place one-ways so the animal leaves and cannot return.", listOf("Find the active hole (oil staining, chew, daylight).", "Mount the door flush; no side gaps.", "Seal every other hole the same day.", "Leave 3-5 days, then remove door and permanent-seal."), "Daytime activity = squirrel until proven otherwise. Check for a second litter before the final seal."),
        Feature("skunk_sop", "Skunk Handling SOP", "Species", "Reduce spray events and neighbor complaints.", listOf("Approach slowly; no flashlight in the face.", "Cover the trap with a towel before moving.", "Work decks and sheds with exclusion, not guesswork.", "Have deodorizer on the truck, not in the cab."), "Most skunk-under-deck jobs are exclusion plus one-way after confirming no kits. Do not pour ammonia as a plan."),
        Feature("groundhog_map", "Groundhog Burrow Mapper", "Species", "Map main and escape holes before trapping.", listOf("Find the fan-shaped dirt mound (main hole).", "Walk 10-30 ft for secondary exits.", "Set at the main hole; collapse unused holes only after capture.", "Repair foundation gaps the same day as removal."), "If you skip the escape hole, the animal is gone and the job looks like a miss."),
        Feature("bird_nest", "Bird Nest Timing", "Species", "Avoid illegal nest takes and failed exclusions.", listOf("Identify species before touching anything.", "Active migratory nests are generally protected.", "Install spikes, netting, or slope after the nest is inactive.", "Fix the attractant: vents, ledges, open soffits."), "If chicks are present, schedule a return window. Sell the exclusion now, install after fledging."),
        Feature("snake_safety", "Snake ID Safety", "Safety", "Treat unknown snakes as venomous until identified.", listOf("Do not pin or grab with bare hands.", "Photograph from a safe distance for ID.", "In NY, rattlesnakes are protected in many areas.", "Seal foundation gaps and rodent food sources."), "Most Hudson Valley yard calls are garter or milk snakes. Still use a hook/tongs. Sell rodent exclusion if mice are present."),
        Feature("opossum_notes", "Opossum Job Notes", "Species", "Fast, low-drama opossum removals.", listOf("They bluff. They rarely fight like raccoons.", "Check for young in the pouch before any relocation.", "Seal the crawl or deck the same visit.", "Do not market them as a disease emergency."), "If young are attached, delay or use a den-box protocol. Same-day exclusion prevents a callback."),
        Feature("wasp_tree", "Wasp / Bee Decision Tree", "Species", "Decide treat, refer, or exclude.", listOf("Honey bees in a wall: refer to a removal specialist when possible.", "Yellowjacket in the ground: treat at dusk, mark the hole.", "Paper wasp under soffit: scrape nest after treatment.", "Always close the cavity or it will be reused."), "Never treat a honey-bee wall and walk away. Comb and honey left behind create a worse follow-up."),
        Feature("attic_score", "Attic Inspection Scorecard", "Inspection", "Score an attic in five minutes.", listOf("Air quality / ammonia / dust (0-20).", "Droppings coverage (0-20).", "Insulation damage (0-20).", "Active entries visible (0-20).", "Electrical / fire / structural risk (0-20)."), "80+ = urgent cleanout + exclusion. 40-79 = exclusion now, cleanout quoted. Under 40 = monitor and seal secondaries."),
        Feature("crawl_hazards", "Crawlspace Hazard Checklist", "Safety", "Do not enter until the space is cleared.", listOf("Look for standing water, live wires, and needles.", "Check for gas, sewage, and low oxygen signs.", "Have a spotter. Phone on. Headlamp plus backup.", "Mark exit path before you crawl in."), "If you cannot see a second way out or the air is bad, decline entry and quote a conditioned-crawl or camera-only inspection."),
        Feature("roof_risk", "Roof Access Risk", "Safety", "Decide ladder, two-person, or no-go.", listOf("Pitch over 6/12 or wet moss = two-person minimum.", "Three-story or brittle slate = consider lift.", "Power lines within reach = stop.", "Frost or high wind = reschedule."), "A chimney-cap job is not worth a fall. Quote the lift. Document why you delayed."),
        Feature("daily_brief", "Daily Field Briefing", "Planning", "A one-page start-of-day brief.", listOf("List jobs by drive order, not by who called first.", "Flag heat, storms, and late-day roof work.", "Pre-load species-specific gear.", "Confirm access codes and dog/tenant notes."), "Start with the farthest AM wildlife-activity stop, then cluster repairs. Leave one emergency slot after 2 pm."),
        Feature("warranty_terms", "Warranty Language Helper", "Closeout", "Plain-language warranty that survives a callback.", listOf("State what is covered: listed openings only.", "State what is not: new storm damage, new construction gaps.", "State customer duties: no feeding wildlife, keep vents clear.", "State term and how to request a return visit."), "Example: We warrant the openings photographed on the invoice for 12 months against the listed species. New holes or customer-altered repairs are extra.")
    )
}
