package com.strobingn.wildlifefieldops.ai

import com.strobingn.wildlifefieldops.ai.local.LocalLlmEngine
import com.strobingn.wildlifefieldops.data.model.Job
import com.strobingn.wildlifefieldops.data.remote.AiService
import javax.inject.Inject
import javax.inject.Singleton

data class FormSuggestions(
    val species: String = "",
    val serviceType: String = "",
    val priority: String = "MEDIUM",
    val notes: String = "",
    val recommendedActions: List<String> = emptyList()
)

data class EstimateSuggestion(
    val tier: String,
    val lineItems: List<String>,
    val totalLow: Int,
    val totalHigh: Int,
    val notes: String
)

/**
 * On-device generative helpers. Uses [LocalLlmEngine] (abliterated llama.cpp GGUF) — never keyword stub lists.
 */
@Singleton
class OnDeviceAIService @Inject constructor(
    private val localLlm: LocalLlmEngine
) {

    suspend fun generateFormSuggestions(
        analysis: AiAnalysisResult,
        recentJobs: List<Job> = emptyList()
    ): FormSuggestions {
        val speciesStr = analysis.species.joinToString(", ")
        val prompt = buildString {
            appendLine("Photo / ML analysis:")
            appendLine("Species tags: $speciesStr")
            appendLine("Damage: ${analysis.damageTypes.joinToString()}")
            appendLine("Suggested service (vision heuristic): ${analysis.suggestedServiceType}")
            appendLine("Suggested priority: ${analysis.suggestedPriority}")
            appendLine("Vision notes: ${analysis.suggestedNotes}")
            if (recentJobs.isNotEmpty()) {
                appendLine("Recent job types: ${recentJobs.take(5).joinToString { it.type }}")
            }
            appendLine()
            appendLine("Return plain text with:")
            appendLine("SPECIES: ...")
            appendLine("SERVICE: ...")
            appendLine("PRIORITY: LOW|MEDIUM|HIGH|URGENT")
            appendLine("NOTES: ...")
            appendLine("ACTIONS:")
            appendLine("- action 1")
            appendLine("- action 2")
        }
        val generated = localLlm.generate(AiService.WILDLIFE_SYSTEM_PROMPT, prompt).getOrNull()
        if (generated != null) {
            return parseFormSuggestions(generated, analysis)
        }
        return FormSuggestions(
            species = speciesStr,
            serviceType = analysis.suggestedServiceType.ifBlank { "Wildlife Inspection & Removal" },
            priority = analysis.suggestedPriority,
            notes = analysis.suggestedNotes.ifBlank {
                "Vision labels only. Download the on-device LLM for generative form fill."
            },
            recommendedActions = listOf(
                "Download on-device LLM in AI Assistant for generative recommendations"
            )
        )
    }

    suspend fun generateEstimateFromAnalysis(
        analysis: AiAnalysisResult,
        photosCount: Int = 1
    ): List<EstimateSuggestion> {
        val prompt = buildString {
            appendLine("Create Good/Better/Best wildlife-removal estimate tiers.")
            appendLine("Species: ${analysis.species.joinToString()}")
            appendLine("Service: ${analysis.suggestedServiceType}")
            appendLine("Damage: ${analysis.damageTypes.joinToString()}")
            appendLine("Vision price hint: ${analysis.estimatedPriceRange}")
            appendLine("Photos: $photosCount")
            appendLine("Return three tiers with line items and low/high totals as plain text.")
        }
        val generated = localLlm.generate(AiService.WILDLIFE_SYSTEM_PROMPT, prompt).getOrNull()
        if (generated != null) {
            return listOf(
                EstimateSuggestion(
                    tier = "AI (on-device)",
                    lineItems = listOf(generated.take(800)),
                    totalLow = analysis.estimatedPriceLow.toInt().coerceAtLeast(0),
                    totalHigh = analysis.estimatedPriceHigh.toInt().coerceAtLeast(0),
                    notes = "Generated by on-device LLM. Review before quoting."
                )
            )
        }
        return emptyList()
    }

    suspend fun analyzeFormForCompliance(formText: String, serviceType: String): List<String> {
        val prompt = "Service type: $serviceType\n\nForm text:\n$formText\n\nList compliance gaps as bullets."
        val generated = localLlm.generate(AiService.WILDLIFE_SYSTEM_PROMPT, prompt).getOrNull()
        if (generated != null) {
            return generated.lines()
                .map { it.trim().removePrefix("-").removePrefix("•").trim() }
                .filter { it.isNotBlank() }
        }
        return listOf(
            "On-device LLM not ready — cannot run generative compliance analysis. Download the model in AI Assistant."
        )
    }

    private fun parseFormSuggestions(raw: String, analysis: AiAnalysisResult): FormSuggestions {
        fun field(name: String): String {
            val line = raw.lineSequence().firstOrNull { it.startsWith("$name:", ignoreCase = true) }
            return line?.substringAfter(':')?.trim().orEmpty()
        }
        val actions = raw.lineSequence()
            .dropWhile { !it.trim().startsWith("ACTIONS", ignoreCase = true) }
            .drop(1)
            .map { it.trim().removePrefix("-").removePrefix("•").trim() }
            .filter { it.isNotBlank() }
            .take(8)
            .toList()
        return FormSuggestions(
            species = field("SPECIES").ifBlank { analysis.species.joinToString(", ") },
            serviceType = field("SERVICE").ifBlank { analysis.suggestedServiceType },
            priority = field("PRIORITY").ifBlank { analysis.suggestedPriority },
            notes = field("NOTES").ifBlank { raw.take(500) },
            recommendedActions = actions
        )
    }
}
